### PR TITLE
mm

### PR DESCRIPTION
**Pull request by lakhan9340**

### CODE REVIEW

**Comment by lakhan9340** [comment]
dsd

**Comment by lakhan9340** [comment]
fff

**Comment by lakhan9340** [comment]
fffgfg

**Comment by Sven-Bo** [comment]
???

**Comment by lakhan9340** [comment]
Hello sven,
I am so sorry for that I was learning how to deploy streamlit webapp from
you channel and you helped me a lot thank you so much and I don't so much
about that's why I generate pull request I don't know what is it and how
it's work.

Thank you

Lakhan jadam

**Comment by lakhan9340** [comment]
Hello Sven,

I’m sorry for the confusion. I was learning how to deploy a Streamlit web
app from your channel, and it helped me a lot. Thank you so much! I don’t
know much about the process, which is why I generated a pull request. I’m
not sure what it is or how it works.

Thank you,
Lakhan Jadam

**Pull request closed without merging**
